# sonarqube-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: my 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonarqube-postgresql:5432/sonarqube
            - name: SONARQUBE_JDBC_USERNAME
              value: sonarqube
            - name: SONARQUBE_JDBC_PASSWORD
              value: admin 
      volumes:
        - name: sonarqube-home
          persistentVolumeClaim:
            claimName: sonarqube-pvc
 
           
