# sonarqube-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: my 
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: sonarqube

